services:
  mongodb:
    image: mongo:7
    container_name: express-template-mongodb
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.4.9-alpine3.21
    container_name: express-template-redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
